
apiVersion: eventstreams.ibm.com/v1beta2
kind: EventStreams
metadata:
  name: event-backbone
  namespace: cp4i-es
spec:
  version: latest
  license:
    accept: true
    use: CloudPakForIntegrationNonProduction
  adminApi: {}
  adminUI: {}
  apicurioRegistry: {}
  collector: {}
  restProducer: {}
  strimziOverrides:
    kafka:
      replicas: 3
      authorization:
        type: custom
        supportsAdminApi: true
        authorizerClass: com.ibm.eventstreams.runas.authorizer.RunAsAuthorizer
      config:
        inter.broker.protocol.version: '3.4'
        log.cleaner.threads: 6
        log.message.format.version: '3.4'
        num.io.threads: 24
        num.network.threads: 9
        num.replica.fetchers: 3
        offsets.topic.replication.factor: 3
        default.replication.factor: 3
        min.insync.replicas: 2
      listeners:
        - name: external
          port: 9094
          tls: true
          authentication:
            type: scram-sha-512
          type: route
        - name: tls
          port: 9093
          authentication:
            type: tls
          type: internal
          tls: true
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            key: kafka-metrics-config.yaml
            name: metrics-config
      storage:
        type: persistent-claim
        class: ocs-storagecluster-ceph-rbd
        size: 10Gi
    zookeeper:
      replicas: 3
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            key: zookeeper-metrics-config.yaml
            name: metrics-config
      storage:
        type: persistent-claim
        class: ocs-storagecluster-ceph-rbd
        size: 10Gi