apiVersion: integration.ibm.com/v1beta1
kind: PlatformNavigator
metadata:
  name: navigator
  namespace: cp4i-pn
spec:
  license:
    accept: true
    license: L-RJON-CJR2RX
  mqDashboard: true
  replicas: 1
  storage:
    class: ocs-storagecluster-cephfs
  version: 2022.4.1-3
